services:

  product-service:
    image: product-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      TZ: Asia/Kolkata

  postgres:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    volumes:
      - ../../data/product-service/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_USER=product_service_dba
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=product-service

networks:
  default:
    name: excoder_network