name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle-build:
    name: Gradle build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: product_service_dba
          POSTGRES_PASSWORD: postgres123
          POSTGRES_DB: product-service
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    permissions:
      contents: read

    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
        java-version: '21'
        distribution: 'temurin'

     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v3

     - name: Build with Gradle Wrapper
       run: ./gradlew build
       env:
        POSTGRES_DATABASE_HOST: localhost
        POSTGRES_DATABASE_PORT: 5432
        POSTGRES_DATABASE_USER: product_service_dba
        POSTGRES_DATABASE_PASSWORD: postgres123
        POSTGRES_DATABASE_NAME: product-service

     - name: Upload build artifacts
       uses: actions/upload-artifact@v4
       with:
         name: gradle-build-artifacts
         path: |
           build/libs

  docker-build-gcr:
    name: Docker build and push to GCR
    needs: gradle-build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-build-artifacts
          path: build/libs
      - name: Display structure of downloaded files
        run: ls -R

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  docker-build-ecr:
    name: Docker build and push to ECR
    needs: gradle-build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-build-artifacts
          path: build/libs

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Amazon ECR Repo
        id: ecr
        uses: int128/create-ecr-repository-action@v1
        with:
          repository: ${{ github.repository }}

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.ecr.outputs.repository-uri }}

      - name: Build, tag, and push the image to Amazon ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
        java-version: '21'
        distribution: 'temurin'

     - name: Generate and submit dependency graph
       uses: gradle/actions/dependency-submission@v3

  deploy:
    name: Pull from ECR and Deploy to AWS App Runner
    needs: [gradle-build, docker-build-ecr]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: app-runner-image-deploy-service
          image: ${{ secrets.ECR_ARN }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: ${{ vars.AWS_REGION }}
          cpu: 1
          memory: 2
          wait-for-service-stability-seconds: 1200

      - name: App Runner URL
        run: echo "App runner URL ${{ steps.deploy-apprunner.outputs.service-url }}"